### ISSUE TITLE
how to add sensor to gateway

### ISSUE THREAD

**Issue by RadekDymak** [lmahmutov/esp32_c6_co2_sensor#2]
Hi please can you give me advice why I can't see demo build sensor in my gateway in tuya app. There is a log file. I see from the log file that, sensor is joined to network. but there is some messagesmay cause, that sensor is not shown in app:

I (83932) ESP_HA_CO2_SENSOR: ZDO signal: NWK Permit Join (0x36), status: ESP_OK
I (109952) ESP_HA_CO2_SENSOR: ZDO signal: NLME Status Indication (0x32), status: ESP_OK

Plase can you give me advice how to add device to this gateway or to another Tahoma switch from somfy.

Log:

I (472) ESP_HA_CO2_SENSOR: ZDO signal: ZDO Config Ready (0x17), status: ESP_FAIL
W (41152) ESP_HA_CO2_SENSOR: Stack BDB Device Start failure with ESP_FAIL status, steering
I (83932) ESP_HA_CO2_SENSOR: ZDO signal: NWK Permit Join (0x36), status: ESP_OK
I (84562) ESP_HA_CO2_SENSOR: ZDO signal: NWK Permit Join (0x36), status: ESP_OK
I (84562) ESP_HA_CO2_SENSOR: Joined network successfully (Extended PAN ID: 5e:2f:a3:65:86:c3:55:af, PAN ID: 0x404c, Channel:15)
I (84662) ESP_HA_CO2_SENSOR: Read attribute response: status(0), cluster(0xa), attribute(0x7), type(0x23), value(207)
I (84662) ESP_HA_CO2_SENSOR: Server time recieved 750165455
I (85422) DEMO MODE: Temp = 1421, Humm = 5712, Press = 179, CO2_Value = 878
I (85422) DEMO MODE: The current date/time is: Mon 11:17:38
....
I (109422) DEMO MODE: Temp = 916, Humm = 3854, Press = 89, CO2_Value = 1790
I (109422) DEMO MODE: The current date/time is: Mon 11:18:02
I (109952) ESP_HA_CO2_SENSOR: ZDO signal: NLME Status Indication (0x32), status: ESP_OK
I (110422) DEMO MODE: Temp = 1566, Humm = 4070, Press = 98, CO2_Value = 1025
I (110422) DEMO MODE: The current date/time is: Mon 11:18:03
....
I (143422) DEMO MODE: Temp = 1371, Humm = 2161, Press = 9, CO2_Value = 2139
I (143422) DEMO MODE: The current date/time is: Mon 11:18:36
I (144292) ESP_HA_CO2_SENSOR: ZDO signal: NWK Permit Join (0x36), status: ESP_OK
I (144422) DEMO MODE: Temp = 1699, Humm = 5010, Press = 12, CO2_Value = 2018
I (144422) DEMO MODE: The current date/time is: Mon 11:18:37

**Comment by lmahmutov** [comment]
Sory i dont have tuya gateway. And never use it. 
I think tuya gateway need specific device manufaturer name and device id.

**Comment by RadekDymak** [comment]
I understand. Which gateway you use? Some home made?

**Comment by lmahmutov** [comment]
> I understand. Which gateway you use? Some home made?

Tested on ZHA (Home assistant) And on Z2M. But this version firmware used custom Co2 cluster and not fully working on all system. Needed custom converter. Espressif add full support later. 
Fully worked on HOMEd coordinator. https://wiki.homed.dev/page/ZigBee/Installation
